# Generated by Django 6.0.1 on 2026-01-28 15:37

import django_nepkit.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=django_nepkit.models.NepaliPhoneNumberField(max_length=10),
        ),
    ]
