# Generated by Django 6.0.1 on 2026-01-28 15:38

import django.utils.timezone
import django_nepkit.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_alter_person_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created_at",
            field=django_nepkit.models.NepaliTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="updated_at",
            field=django_nepkit.models.NepaliTimeField(auto_now=True),
        ),
    ]
