# Generated by Django 6.0.1 on 2026-01-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_alter_person_birth_date_alter_person_birth_date_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="birth_date_en",
            new_name="birth_date_ne",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="district_en",
            new_name="district_ne",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="municipality_en",
            new_name="municipality_ne",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="province_en",
            new_name="province_ne",
        ),
    ]
