# Generated by Django 6.0.1 on 2026-01-28 15:39

import django_nepkit.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0003_person_created_at_person_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=django_nepkit.models.NepaliDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=django_nepkit.models.NepaliDateField(auto_now=True),
        ),
    ]
