# Generated by Django 6.0.1 on 2026-01-28 16:55

import django_nepkit.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0004_alter_person_created_at_alter_person_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=django_nepkit.models.NepaliDateTimeField(
                auto_now_add=True, blank=True, editable=False, max_length=19
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="updated_at",
            field=django_nepkit.models.NepaliDateTimeField(
                auto_now=True, blank=True, editable=False, max_length=19
            ),
        ),
    ]
