# Generated by Django 6.0.1 on 2026-01-30 09:47

import django_nepkit.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0006_alter_citizen_district_alter_citizen_province"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditedPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("birth_date", django_nepkit.models.NepaliDateField(max_length=10)),
                (
                    "created_at",
                    django_nepkit.models.NepaliDateTimeField(
                        auto_now_add=True, blank=True, editable=False, max_length=19
                    ),
                ),
            ],
        ),
    ]
